### ISSUE TITLE
Error for pagination in blog

### ISSUE THREAD

**Issue by Misagh90** [Cyber-Duck/Silverstripe-SEO#22] opened 2019-01-01 13:22 UTC
Hi,
When i try next page or page number in blog i see this error
![screenshot 71](https://user-images.githubusercontent.com/6697222/50573214-93823780-0de4-11e9-8fe1-7c58675dba13.png)
I changed the (`CurrentPage() == 2`) in these code (`if($this->CurrentPage() == 2) {
            $url = $this->request->getURL(false);`) in src\ORM\SeoPaginatedList.php into another number(e.g. `CurrentPage() == 0` or `CurrentPage() == 1000`) then it's working fine

**Comment by Andrew-Mc-Cormack** [comment] 2019-01-02 14:58
Are you using a custom controller for the blog?

**Comment by Misagh90** [comment] 2019-01-03 06:04
No, i only add a $many_many filed in my blog post.

**Comment by Andrew-Mc-Cormack** [comment] 2019-02-05 15:51
Fixed on develop branch, will be in a release tomorrow. Think the issue is the request property is not an  object but an array. Cant remember exactly but it is fixed by a custom blog controller also by calling parent::index(); in the custom blog controller index method.

**Closed** 2019-02-05 15:52 UTC
