### ISSUE TITLE
Call to undefined method SilverStripe\Config\Collections\CachedConfigCollection::remove()

### ISSUE THREAD

**Issue by Edvardas-idea** [Cyber-Duck/Silverstripe-SEO#13] opened 2018-03-07 08:50 UTC
Just installed new stable version(4.1.0) of this module, having problem on SS 4.0.3 accessing /admin/seo-admin/. Error:

Emergency] Uncaught Error: Call to undefined method SilverStripe\Config\Collections\CachedConfigCollection::remove()
GET /admin/seo-admin/

Line 257 in /var/www/public/vendor/cyber-duck/silverstripe-seo/src/Model/Extension/SeoPageExtension.php

**Comment by Andrew-Mc-Cormack** [comment] 2018-03-09 10:30
Strange, seems okay for me. Will have a look at this later this evening.

**Comment by davidcraigmyle** [comment] 2018-04-10 10:50
Also having this problem, the line 
`Config::inst()->remove($this->owner->class, 'summary_fields');`
Seems to be the issue as remove no longer exists.

**Comment by rodwin** [comment] 2018-06-06 23:02
@davidcraigmyle have you figured this out?
Thanks

**Comment by J-Pielage** [comment] 2018-07-23 06:59
@davidcraigmyle I was wondering if there is any news on this issue. I installed dev-master and get the same error as described by @Edvardas-idea.

**Comment by davidcraigmyle** [comment] 2018-07-23 08:17
@rodwin @J-Pielage I am afraid i haven't had time to look at it as i don't use the module often.

**Comment by Andrew-Mc-Cormack** [comment] 2018-07-25 11:21
Hi. For SilverStripe 4.1 please use the 4.2 branch (its a bit confusing but that 4.1 branch was created before the release of SilverStripe 4.1 and the change in the public folder structure). There was an issue with requirements which is now fixed, let me know if you still have issues or the issue is fixed for you. In composer:

"cyber-duck/silverstripe-seo": "4.2.*"

**Closed** 2018-07-29 10:45 UTC

**Comment by J-Pielage** [comment] 2018-07-31 11:24
Hi, sorry for my late response. 

I still get the same error when I visit the overview page by clicking the icon in the CMS-sidebar.
I just did a clean SilverStripe installation (dev-master) and installed the 4.2.* SEO version. Any change to look in it some more?

**Comment by lars-lemon8** [comment] 2018-09-13 08:41
This issue is still present..

**Comment by Dennisprins93** [comment] 2019-01-27 16:01
This issue still persist in January 2019. I'm getting the error as wel, SS version 4.3.

**Comment by PVerberkmoes** [comment] 2020-12-15 08:23
This issue is still present with SS 4.6.1 and 4.5.1 SEO
